<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use GuzzleHttp\Client;
use Symfony\Component\Routing\Annotation\Route;

class ChatController extends AbstractController
{
    #[Route('/chat', name: 'app_chat')]
    public function index(Request $request): Response
    {
        // Replace 'YOUR_API_KEY' with your actual OpenAI API key
        $apiKey = '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';
        $client = new Client([
            'base_uri' => 'https://api.openai.com/v1/',
            'headers' => [
                'Authorization' => 'Bearer ' . $apiKey,
            ],
        ]);

        // Set a default response variable
        $botResponse = '';

        // Check if the form has been submitted
        if ($request->isMethod('POST')) {
            $userInput = $request->request->get('user_input');

            // Call the OpenAI API to get a response
            $response = $client->post('engines/gpt-3.5-turbo/completions', [
                'json' => [
                    'prompt' => $userInput,
                    'max_tokens' => 50,
                ],
            ]);

            $responseData = json_decode($response->getBody(), true);

            // Get the response generated by the chatbot
            $botResponse = $responseData['choices'][0]['text'];
        }

        return $this->render('chat/index.html.twig', [
            'botResponse' => $botResponse,
        ]);
    }
}


